name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.10-slim
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Install Zip
        run: apt-get update && apt-get install -y zip
      - name: Deploy
        uses: TryGhost/action-deploy-theme@v1.2.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: 'node_modules/*'
