name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.10-slim
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
